### PR TITLE
Fix for digits in URLs

### PR DESCRIPTION
**Pull request by nrk**
Hi Benjamin,

I slightly changed the definition of an _unreserved character_ for an URI to prevent HttpMachine from breaking when parsing requests that contain digit characters in the path part of the URL (e.g. **http://127.0.0.1/foo_500.html**).

### CODE REVIEW

**Comment by bvanderveen** [comment]
Thanks for this pull! Apologies for not replying sooner, life's been pretty crazy the past few weeks. And wouldn't you know it I'm going out of town again tomorrow at 4:45am.

Any interest in making a test to demonstrate that this is fixed? ;) I was hoping to knock out all of my outstanding email TODO's (including this one) before heading out of town. Unfortunately it's midnight and I really must stop with my laptop, but I wanted to acknowledge this before going away. 

Again, sorry for the delay, and many thanks for the patch!

**Comment by nrk** [comment]
Don't worry about the delay, being busy is part of life ;-)

I haven't added a formal test just because I wasn't really sure about how your tests for httpmachine are organized, but I suppose a test right before [this one](https://github.com/bvanderveen/httpmachine/blob/master/HttpMachine.Tests/TestRequest.cs#L89) should do it.

Anyway I'll add a test with the next commit to this pull request, not sure if I can get it done by the end of the day since I don't have access to my dev environment right now.

**Comment by bvanderveen** [comment]
Thanks for understanding. :) That looks like a great place to add the test request. You'll also have to add another NUnit test which exercises it.

**Comment by nrk** [comment]
Done! (and now I'm the one apologizing for the delay ;-)).

I hope everything is fine now, but let me know if I should adjust something before you merge my commits.

Thanks!

**Comment by dalager** [comment]
Did  you add other legal characters as well? adding querystring params is sort of hard when  you can't use the '=' character ;)

**Comment by bvanderveen** [comment]
Finally closed this up. Thanks Daniele!

**Comment by nrk** [comment]
@bvanderveen awesome, thanks!

@dalager why? The definition for `uri_query` includes all the needed characters, including `=` (see `reserved`)

**Comment by dalager** [comment]
Ah, it works now.
I had some problems with querystrings in kayak 0.6 (before the nuget
package) but they are gone now.
Sorry.

On Mon, May 30, 2011 at 5:57 PM, nrk <
reply@reply.github.com>wrote:

> @bvanderveen awesome, thanks!
> 
> @dalager why? The definition for `uri_query` includes all the needed
> characters, including `=` (see `reserved`)
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/bvanderveen/httpmachine/pull/3#issuecomment-1262067

## 

Christian Dalager
Milnersvej 16
3400 Hillerød
mob: 61 770 990
www: http://dalager.com

**Pull request merged**
